# Project 02 - Image Processing

## Student Information

- Full name: Nguyễn Phúc Khang
- Student ID: 22127180
- Class: 22CLC08

## Required Libraries

In [1]:
import numpy as np

x = np.arange(5)
y = np.arange(3)
print(x)
print(y)

x, y = np.meshgrid(x,  y)
print(x)
print(y)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([2, 2, 2])

e = np.array([[1, 2], 
              [3, 4]])

f = np.array([[5, 6], 
              [7, 8]])

g = np.array([[9, 10]])

res = np.einsum('ij,ij->ij', e, f)
print(res)

[0 1 2 3 4]
[0 1 2]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
[[ 5 12]
 [21 32]]


## Function Definitions

In [2]:
def read_img(img_path):
    '''
    Read image from img_path

    Parameters
    ----------
    img_path : str
        Path of image

    Returns
    -------
        Image
    '''

    # YOUR CODE HERE


def show_img(img):
    '''
    Show image

    Parameters
    ----------
    img : <your type>
        Image
    '''

    # YOUR CODE HERE


def save_img(img, img_path):
    '''
    Save image to img_path

    Parameters
    ----------
    img : <your type>
        Image
    img_path : str
        Path of image
    '''

    # YOUR CODE HERE


#--------------------------------------------------------------------------------
# YOUR FUNCTIONS HERE

<ins>Note:</ins> For clarity, include docstrings with each function.

## Your tests

In [3]:
# YOUR CODE HERE

## Main FUNCTION

In [4]:
# YOUR CODE HERE

In [5]:
# Call main function